### ISSUE TITLE
comments 생성 부분에서 문제가 발생했습니다.

### ISSUE THREAD

**Issue by lec2528** [lec2528/Lv5_Layered-Architecture-Pattern#1]
**총 두가지 에러가 반복적으로 발생중입니다.

api는 /post/:postId/comment로 사용중입니다.** 

첫번째 에러 코드 입니다. parameter로 받아오는 postId값에 문제가 있는것 같은데 어디서 문제인지 모르겠습니다.

```
Executing (default): SELECT `userId`, `email`, `nickname`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `Users` WHERE `Users`.`userId` = 1;
userId 1
postId 1
C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\instance-validator.js:50
      throw new sequelizeError.ValidationError(null, this.errors);
            ^

ValidationError [SequelizeValidationError]: notNull Violation: Comments.postId cannot be null
    at InstanceValidator._validate (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\instance-validator.js:50:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InstanceValidator._validateAndRunHooks (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\instance-validator.js:60:7)
    at async InstanceValidator.validate (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\instance-validator.js:54:12)
    at async Comments.save (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\model.js:2426:7)
    at async Comments.create (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\model.js:1362:12)
    at async CommentsRepository.createComments (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\repositories\comments.repository.js:14:21)
    at async CommentsService.createComments (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\services\comments.services.js:30:5)
    at async createComments (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\controllers\comments.controller.js:29:28) {
  errors: [
    ValidationErrorItem {
      message: 'Comments.postId cannot be null',
      type: 'notNull Violation',
      path: 'postId',
      value: null,
      origin: 'CORE',
      instance: Comments {
        dataValues: {
          createdAt: 2023-07-14T09:46:59.914Z,
          updatedAt: 2023-07-14T09:46:59.915Z,
          commentId: null,
          postId: undefined,
          userId: '댓글생성테스트',
          nickname: '1',
          content: 1
        },
        _previousDataValues: { userId: undefined, nickname: undefined, content: undefined },
        uniqno: 1,
        _changed: Set(3) { 'userId', 'nickname', 'content' },
        _options: {
          isNewRecord: true,
          _schema: null,
          _schemaDelimiter: '',
          attributes: undefined,
          include: undefined,
          raw: undefined,
          silent: undefined
        },
        isNewRecord: true
      },
      validatorKey: 'is_null',
      validatorName: null,
      validatorArgs: []
    }
  ]
}
```

두번째 에러코드 입니다.
외래키 제약조건을 위반했다는 내용입니다.

Executing (default): SELECT `userId`, `email`, `nickname`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `Users` WHERE `Users`.`userId` = 1;
userId 1
postId 1
Executing (default): INSERT INTO `Comments` (`commentId`,`userId`,`postId`,`nickname`,`content`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Query.run (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
    at C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.insert (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async Comments.save (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\model.js:2490:35)
    at async Comments.create (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\sequelize\lib\model.js:1362:12)
    at async CommentsRepository.createComments (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\repositories\comments.repository.js:14:21)
    at async CommentsService.createComments (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\services\comments.services.js:30:5)
    at async createComments (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\controllers\comments.controller.js:29:28) {
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`Lv5_Layered_Architecture_Pattern`.`Comments`, CONSTRAINT `Comments_ibfk_1` FOREIGN KEY (`postId`) REFERENCES `Posts` (`postId`) ON DELETE CASCADE)
      at Packet.asError (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Execute.execute (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\connection.js:492:32)
      at PacketParser.onPacket (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`Lv5_Layered_Architecture_Pattern`.`Comments`, CONSTRAINT `Comments_ibfk_1` FOREIGN KEY (`postId`) REFERENCES `Posts` (`postId`) ON DELETE CASCADE)',
    sql: 'INSERT INTO `Comments` (`commentId`,`userId`,`postId`,`nickname`,`content`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);',
    parameters: [
      '댓글생성테스트',
      'test25',
      '1',
      1,
      '2023-07-14 05:35:01',
      '2023-07-14 05:35:01'
    ]
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`Lv5_Layered_Architecture_Pattern`.`Comments`, CONSTRAINT `Comments_ibfk_1` FOREIGN KEY (`postId`) REFERENCES `Posts` (`postId`) ON DELETE CASCADE)
      at Packet.asError (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Execute.execute (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\connection.js:492:32)
      at PacketParser.onPacket (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\LEC\Desktop\web\Lv5_LayeredArchitecturePattern\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`Lv5_Layered_Architecture_Pattern`.`Comments`, CONSTRAINT `Comments_ibfk_1` FOREIGN KEY (`postId`) REFERENCES `Posts` (`postId`) ON DELETE CASCADE)',
    sql: 'INSERT INTO `Comments` (`commentId`,`userId`,`postId`,`nickname`,`content`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);',
    parameters: [
      '댓글생성테스트',
      'test25',
      '1',
      '2023-07-14 05:35:01',
      '2023-07-14 05:35:01'
    ]
  },
  sql: 'INSERT INTO `Comments` (`commentId`,`userId`,`postId`,`nickname`,`content`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?);',
  parameters: [
    '댓글생성테스트',
    'test25',
    '1',
    1,
    '2023-07-14 05:35:01',
    '2023-07-14 05:35:01'
  ],
  table: 'Posts',
  fields: [ 'postId' ],
  value: 'test25',
  index: 'Comments_ibfk_1',
  reltype: 'child'
}

**Comment by lec2528** [comment]
불필요 인자로 인한 에러로 판단했고 인자들을 삭제해준이후 정상작동하는거 같습니다.
